Allow creation of items in Zabbix
tverlaan/exometer_zabbix pull request #3
Opened 2017-11-09 16:31 UTC by jeanparpaillon

This series of commits add the possibility to create the items as zabbix_trapper.
Items are associated to an app and a template, which can also be created automatically.
By default, template and apps are named after first element of item name.

2017-11-17 13:18 UTC, jeanparpaillon commented
This pr add support for creating items in zabbix, creating also templates and applications to attach item to.
Template and applications names are configurable.
Creation is done through JSON-RPC Zabbix interface.

2017-11-19 19:14 UTC, tverlaan commented
Hi, thanks for submitting a PR! I see some useful improvements there!
I need a little bit more time to review it, I'll get back to you later this week!

2017-11-20 08:32 UTC, jeanparpaillon commented
Thanks for having a look at it.
Don't hesitate to suggest modifications...

2017-12-05 10:15 UTC, tverlaan requested changes
Thanks again for submitting a PR. I'd like a few things improved, I hope it is not to much trouble. One remark in general, can you please put the `|>` operator at the beginning of the (next) line and not at the end of the current one.

Please let me know if you need some help with any of the remarks. I can also spend some time on it if that's what you prefer.

2017-12-05 10:15 UTC, tverlaan commented on mix.exs
> +      {:exometer_core, github: "Feuerlabs/exometer_core"},
this will break uploading to hex.pm, can you change it back? or change it to a newer version on hex?

2017-12-05 10:15 UTC, tverlaan commented on lib/exometer/report/zabbix/utils.ex
> +  alias :exometer, as: Exometer
I prefer to not alias erlang modules as it makes reading the code harder to understand. Especially since `alias Exometer` would create the exact same alias but is entirely different from this one.

2017-12-05 10:15 UTC, tverlaan commented on lib/exometer/report/zabbix/utils.ex
> +  @zbx_type_text      4
please put the module attributes at the top :-)

2017-12-05 10:15 UTC, tverlaan commented on README.md
> +* `name`: is the name of the item (default: "Exomeeter <key>")
typo in exomeeter ;-)

2017-12-05 10:15 UTC, tverlaan commented on lib/exometer/report/zabbix.ex
> +      {:ok, _} = Rpc.start_link(opts)
There are a view considerations here, I'll list them:

1. This blocks until RPC connects, that is not preferable as we're blocking gathering and sending metrics
2. If RPC fails, now exometer reporter for zabbix won't start at all

I think it would be best if this is non-blocking (so no actuall connect in the init function of RPC module. Secondly, we shouldn't check :ok or :error here. If we want that kind of behaviour we should put the RPC module under a supervisor.

2017-12-05 10:15 UTC, tverlaan commented on lib/exometer/report/zabbix.ex
> +  def exometer_subscribe(metric, datapoint, interval, extra, %__MODULE__{} = state) do
👍

2017-12-12 07:57 UTC, jeanparpaillon commented on lib/exometer/report/zabbix.ex
> +      {:ok, _} = Rpc.start_link(opts)
I've initially implemented it with a supervisor, but it implies exometer_zabbix being an app, hence need for starting it, hence breaking existing use of exometer_zabbix.
But if you're ok with that, I can implement a supervising tree. I agree it is more robust.

2020-11-17 21:39 UTC, tverlaan commented
Closing the PR as the feedback is not integrated. Please re-open or create a new one if you feel strongly about this PR. Thank you for the effort either way :-)

2020-11-17 21:39 UTC, closed without merging